# Generated by Django 5.2.3 on 2026-04-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coformacion', '0010_sync_with_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_estudiantes/'),
        ),
    ]
