# Generated by Django 5.2.3 on 2026-04-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coformacion', '0011_add_foto_to_estudiantes'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE estudiantes_eps (
                eps_id INT AUTO_INCREMENT PRIMARY KEY,
                nombre VARCHAR(250) NOT NULL UNIQUE,
                codigo VARCHAR(400)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS estudiantes_eps;"
        ),
    ]

